CREATE TABLE IF NOT EXISTS public.User (id TEXT NOT NULL PRIMARY KEY, createdAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), email TEXT NOT NULL UNIQUE, name TEXT NULL);
alter table public.User alter column name set NOT NULL;

CREATE TABLE IF NOT EXISTS public.Post (id INTEGER NOT NULL PRIMARY KEY, createdAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), updatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), published bool NOT NULL DEFAULT false, title TEXT NOT NULL, authorId TEXT NULL, CONSTRAINT User_fkey FOREIGN KEY (authorId) REFERENCES public.User(id) ON DELETE RESTRICT ON UPDATE CASCADE);

