name: 'CI/CD pipeline'

on:
  push:
    branches: [ '**' ]

env: 
  CARGO_TERM_COLOR: always

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
      - run: npm install
      - run: npm run test
      - run: npm run build
        run: yarn
        run: npx playwright install --with-deps
        run: yarn build-storybook --quiet
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"
  # build_and_test:
  #   name: Rust project - latest
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./db/orm/ast
  #   strategy:
  #     matrix:
  #       toolchain:
  #         - stable
  #         - beta
  #         - nightly
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
  #     - run: cargo build --verbose
  #     - run: cargo test --verbose