name: 'CI/CD pipeline'

on:
  push:
    branches: [ '**' ]

env: 
  CARGO_TERM_COLOR: always

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
      - run: npm install
      - run: npm run test
      - run: npm run build
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cd orm/ast
      - run: cargo build --verbose
      - run: cargo test --verbose